# Generated by Django 4.2.25 on 2025-10-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of this dish', null=True, upload_to='menu_images/'),
        ),
    ]
